package main

// Numerical-determinism audit dump (Go side).
//
// Guarded by the NUMERICAL_AUDIT_SCENARIOS environment variable; without it
// the test skips so normal `go test ./...` runs are unaffected.
//
// The audit drives the REAL production engine (dispatchArmy, stepSimulation,
// evaluateAIMove) over exhaustive boundary-case sets generated by
// test/scripts/numerical_audit.mjs and compares bit-for-bit results with the
// TypeScript engine:
//
//   - progress cases: a single marching army per (battlefield distance,
//     army-speed multiplier, stable-source multiplier) combination; records
//     the arrival step, arrival progress bits, and whether the army ever
//     lands within 1e-12 of the progress=1.0 decision boundary.
//   - production cases: one owned territory per (base rate, production
//     multiplier, territory-type multiplier) combination; records the first
//     unit-grant step, final unit count, and final accumulator bits.
//   - ai cases: synthetic boards per (battlefield, source units, target
//     geometry) including exact-tie twins; records the AI decision.
//
// Any bit-level difference between the engines on these decision boundaries
// is reported by the orchestrator; arrival-step or AI-decision differences
// are outcome-changing and must be fixed.

import (
	"encoding/json"
	"math"
	"os"
	"strconv"
	"testing"
)

type auditProgressCase struct {
	ID                string  `json:"id"`
	SourceX           float64 `json:"sourceX"`
	SourceY           float64 `json:"sourceY"`
	TargetX           float64 `json:"targetX"`
	TargetY           float64 `json:"targetY"`
	SourceStable      bool    `json:"sourceStable"`
	TravelMultiplier  float64 `json:"travelMultiplier"`
	MaxSteps          int     `json:"maxSteps"`
}

type auditProductionCase struct {
	ID              string  `json:"id"`
	ProductionRate  float64 `json:"productionRate"`
	TerritoryType   string  `json:"territoryType"`
	MaxUnits        int     `json:"maxUnits"`
	MaxSteps        int     `json:"maxSteps"`
}

type auditAIPatch struct {
	ID    string  `json:"id"`
	Owner *string `json:"owner"`
	Units *int    `json:"units"`
}

type auditAICase struct {
	ID            string         `json:"id"`
	BattlefieldID string         `json:"battlefieldId"`
	Patches       []auditAIPatch `json:"patches"`
}

type auditScenarios struct {
	ProgressCases   []auditProgressCase   `json:"progressCases"`
	ProductionCases []auditProductionCase `json:"productionCases"`
	AICases         []auditAICase         `json:"aiCases"`
}

type auditProgressResult struct {
	ID                  string  `json:"id"`
	ArrivalStep         int     `json:"arrivalStep"` // 0 = never arrived within maxSteps
	ArrivalProgress     float64 `json:"arrivalProgress"`
	ArrivalProgressBits uint64  `json:"arrivalProgressBits"`
	SpeedBits           uint64  `json:"speedBits"`
	MinBoundaryGap      float64 `json:"minBoundaryGap"`
}

type auditProductionResult struct {
	ID              string  `json:"id"`
	FirstGrantStep  int     `json:"firstGrantStep"` // 0 = never granted within maxSteps
	FinalUnits      int     `json:"finalUnits"`
	FinalAccumulator float64 `json:"finalAccumulator"`
	AccumulatorBits uint64  `json:"accumulatorBits"`
	MinBoundaryGap  float64 `json:"minBoundaryGap"`
	GrantsHash      string  `json:"grantsHash"` // FNV-1a over per-step granted counts, hex
	Grants          []int   `json:"grants"`     // per-step granted units (for first-divergence reporting)
}

type auditAIResult struct {
	ID      string `json:"id"`
	OK      bool   `json:"ok"`
	FromID  string `json:"fromId"`
	ToID    string `json:"toId"`
}

type auditOutput struct {
	Progress   []auditProgressResult   `json:"progress"`
	Production []auditProductionResult `json:"production"`
	AI         []auditAIResult         `json:"ai"`
}

func floatBits(value float64) uint64 {
	return math.Float64bits(value)
}

// TestNumericalAuditDump replays audit cases through the real engine and
// dumps results when NUMERICAL_AUDIT_SCENARIOS is set.
func TestNumericalAuditDump(t *testing.T) {
	scenariosPath := os.Getenv("NUMERICAL_AUDIT_SCENARIOS")
	if scenariosPath == "" {
		t.Skip("NUMERICAL_AUDIT_SCENARIOS not set; skipping numerical audit dump")
	}
	outputPath := os.Getenv("NUMERICAL_AUDIT_OUTPUT")
	if outputPath == "" {
		outputPath = "numerical_audit_go_results.json"
	}

	raw, err := os.ReadFile(scenariosPath)
	if err != nil {
		t.Fatalf("failed to read audit scenarios: %v", err)
	}
	var scenarios auditScenarios
	if err := json.Unmarshal(raw, &scenarios); err != nil {
		t.Fatalf("failed to parse audit scenarios: %v", err)
	}

	output := auditOutput{
		Progress:   make([]auditProgressResult, 0, len(scenarios.ProgressCases)),
		Production: make([]auditProductionResult, 0, len(scenarios.ProductionCases)),
		AI:         make([]auditAIResult, 0, len(scenarios.AICases)),
	}

	for _, progressCase := range scenarios.ProgressCases {
		result := runAuditProgressCase(progressCase)
		output.Progress = append(output.Progress, result)
	}

	for _, productionCase := range scenarios.ProductionCases {
		result := runAuditProductionCase(productionCase, t)
		output.Production = append(output.Production, result)
	}

	for _, aiCase := range scenarios.AICases {
		// Build the full real battlefield board, then apply the case patches.
		// evaluateAIMove only considers territories present in the
		// battlefield order list, so boards must be the real ones.
		territories := CreateTerritoriesForBattlefield(PlayerUpgradeModifiers{}, PlayerUpgradeModifiers{}, aiCase.BattlefieldID)
		for _, patch := range aiCase.Patches {
			territory, exists := territories[patch.ID]
			if !exists {
				t.Fatalf("ai case %s patches unknown territory %s", aiCase.ID, patch.ID)
			}
			if patch.Owner != nil {
				territory.Owner = Team(*patch.Owner)
			}
			if patch.Units != nil {
				territory.Units = *patch.Units
			}
			territories[patch.ID] = territory
		}
		state := GameState{
			BattlefieldID: aiCase.BattlefieldID,
			Territories:   territories,
			Status:        "playing",
		}
		fromID, toID, ok := evaluateAIMove(state)
		output.AI = append(output.AI, auditAIResult{ID: aiCase.ID, OK: ok, FromID: fromID, ToID: toID})
	}

	payload, err := json.Marshal(output)
	if err != nil {
		t.Fatalf("failed to marshal audit output: %v", err)
	}
	if err := os.WriteFile(outputPath, payload, 0o600); err != nil {
		t.Fatalf("failed to write audit output: %v", err)
	}
	t.Logf("wrote audit results: %d progress, %d production, %d ai cases",
		len(output.Progress), len(output.Production), len(output.AI))
}

// runAuditProgressCase drives the real dispatchArmy + stepSimulation path for
// a single marching army and observes the arrival decision boundary.
func runAuditProgressCase(progressCase auditProgressCase) auditProgressResult {
	// Territory geometry only feeds the real dispatch arithmetic; combat
	// details are irrelevant to march timing.
	source := Territory{
		ID: "src", Name: "Source", X: progressCase.SourceX, Y: progressCase.SourceY, Radius: 20,
		Owner: TeamPlayer, Units: 40, MaxUnits: 65, ProductionRate: 0, Tier: 1, Type: TerritoryFortress,
	}
	if progressCase.SourceStable {
		source.Type = TerritoryStable
	}
	target := Territory{
		ID: "tgt", Name: "Target", X: progressCase.TargetX, Y: progressCase.TargetY, Radius: 20,
		Owner: TeamNeutral, Units: 0, MaxUnits: 65, ProductionRate: 0, Tier: 1, Type: TerritoryFortress,
	}
	state := GameState{
		BattlefieldID: "crown_cross",
		Territories:   map[string]Territory{"src": source, "tgt": target},
		Armies:        []MarchingArmy{},
		Status:        "playing",
		// March timing must not be truncated by the 90s match limit: the only
		// terminator is arrival or maxSteps.
		TimeLimitSeconds: 1e18,
	}
	// The real production dispatch path: distance via math.Hypot, duration via
	// the same expression as dispatchArmy, speed = 1/duration.
	if err := dispatchArmy(&state, "src", "tgt", TeamPlayer, progressCase.TravelMultiplier, "audit_army"); err != nil {
		panic(err)
	}
	army := state.Armies[0]
	result := auditProgressResult{
		ID:        progressCase.ID,
		SpeedBits: floatBits(army.Speed),
	}

	accumulators := map[string]float64{}
	minBoundaryGap := math.Inf(1)
	for step := 1; step <= progressCase.MaxSteps; step++ {
		if state.Status != "playing" {
			break
		}
		var next ProgressProbe
		state, _, next = stepSimulationProbe(state, accumulators, PvpSimulationTick, army.ID)
		accumulators = next.accumulators
		if next.progressValid {
			gap := math.Abs(next.progress - 1.0)
			if gap < minBoundaryGap {
				minBoundaryGap = gap
			}
			if next.progress >= 1.0 {
				result.ArrivalStep = step
				result.ArrivalProgress = next.progress
				result.ArrivalProgressBits = floatBits(next.progress)
				break
			}
		}
	}
	if !math.IsInf(minBoundaryGap, 1) {
		result.MinBoundaryGap = minBoundaryGap
	}
	return result
}

// ProgressProbe carries the pre-arrival progress of the audited army so the
// boundary gap can be measured before the army is consumed by combat.
type ProgressProbe struct {
	progressValid  bool
	progress       float64
	accumulators   map[string]float64
}

// stepSimulationProbe mirrors the army-movement half of the real
// stepSimulation loop exactly (same expression shape and order), reporting
// the audited army's next progress before the arrival resolution. Combat and
// generation run through the real resolveArrival/tickGeneration.
func stepSimulationProbe(state GameState, accumulators map[string]float64, delta float64, armyID string) (GameState, []combatResult, ProgressProbe) {
	probe := ProgressProbe{}
	state.ElapsedTimeSeconds += delta
	state.Stats.MatchDurationSeconds = state.ElapsedTimeSeconds
	remaining := make([]MarchingArmy, 0, len(state.Armies))
	resolved := []combatResult{}
	for _, army := range state.Armies {
		nextProgress := army.Progress + army.Speed*delta
		if army.ID == armyID {
			probe.progressValid = true
			probe.progress = nextProgress
		}
		if nextProgress >= 1 {
			target, exists := state.Territories[army.TargetID]
			if exists {
				combat := resolveArrival(target, army.Units, army.Owner)
				target.Owner = combat.newOwner
				target.Units = combat.remaining
				state.Territories[army.TargetID] = target
				resolved = append(resolved, combat)
			}
		} else {
			army.Progress = nextProgress
			remaining = append(remaining, army)
		}
	}
	state.Armies = remaining
	accumulators = tickGeneration(&state, accumulators, delta)
	// Terminate on elimination/time limit exactly like the real loop.
	playerTerritories, enemyTerritories := 0, 0
	for _, id := range territoryOrderForBattlefield(state.BattlefieldID) {
		territory := state.Territories[id]
		if territory.Owner == TeamPlayer {
			playerTerritories++
		} else if territory.Owner == TeamEnemy {
			enemyTerritories++
		}
	}
	if state.ElapsedTimeSeconds >= state.TimeLimitSeconds {
		state.Status = "draw"
	}
	return state, resolved, probe
}

// runAuditProductionCase drives the real tickGeneration (via
// stepSimulationProbe's generation call) for a single owned territory and
// observes the floor(acc) unit-grant boundary.
func runAuditProductionCase(productionCase auditProductionCase, t *testing.T) auditProductionResult {
	territoryType := TerritoryType(productionCase.TerritoryType)
	// The audited territory must use a real battlefield ID: tickGeneration
	// iterates the authoritative battlefield order list and ignores anything
	// outside it (that is a load-bearing engine behavior, not an artifact).
	state := GameState{
		BattlefieldID: "crown_cross",
		Territories: map[string]Territory{
			"n_center": {
				ID: "n_center", Name: "Audit", X: 200, Y: 360, Radius: 20,
				Owner: TeamPlayer, Units: 0, MaxUnits: productionCase.MaxUnits,
				ProductionRate: productionCase.ProductionRate, Tier: 1, Type: territoryType,
			},
		},
		Armies:           []MarchingArmy{},
		Status:           "playing",
		TimeLimitSeconds: 1e18,
	}
	result := auditProductionResult{ID: productionCase.ID, Grants: make([]int, 0, productionCase.MaxSteps)}
	grantsHash := uint64(14695981039346656037)
	accumulators := map[string]float64{}
	minBoundaryGap := math.Inf(1)
	for step := 1; step <= productionCase.MaxSteps; step++ {
		unitsBefore := state.Territories["n_center"].Units
		// The real generation tick: territoryProductionMultiplier is applied
		// inside tickGeneration exactly as in production.
		next := tickGeneration(&state, accumulators, PvpSimulationTick)
		accumulators = next
		territory := state.Territories["n_center"]

		// Reconstruct the pre-floor accumulator (accumulators_after +
		// granted units): the engines disagree on a grant only when this
		// value sits within rounding drift of an integer boundary.
		granted := territory.Units - unitsBefore
		result.Grants = append(result.Grants, granted)
		grantsHash ^= uint64(granted)
		grantsHash *= 1099511628211
		preFloor := accumulators["n_center"] + float64(granted)
		// Skip capped/reset steps (preFloor == 0): the accumulator is forced
		// to zero at capacity, which is not a rounding boundary.
		if preFloor > 0 {
			gap := math.Abs(preFloor - math.Round(preFloor))
			if gap < minBoundaryGap {
				minBoundaryGap = gap
			}
			// Bit-level trace for a diagnosed case: every grant step and every
			// step within 1e-9 of an integer boundary.
			if traceCase := os.Getenv("NUMERICAL_AUDIT_TRACE"); traceCase == productionCase.ID {
				if granted > 0 || gap < 1e-9 {
					t.Logf("step %d preFloor=%v bits=%016x granted=%d", step, preFloor, floatBits(preFloor), granted)
				}
			}
		}
		if result.FirstGrantStep == 0 && territory.Units > 0 {
			result.FirstGrantStep = step
		}
		if step == productionCase.MaxSteps {
			result.FinalUnits = territory.Units
			result.FinalAccumulator = accumulators["n_center"]
			result.AccumulatorBits = floatBits(accumulators["n_center"])
		}
	}
	if !math.IsInf(minBoundaryGap, 1) {
		result.MinBoundaryGap = minBoundaryGap
	}
	result.GrantsHash = strconv.FormatUint(grantsHash, 16)
	return result
}
