import { Territory } from './types.js';
import type { PlayerUpgradeModifiers } from './upgrades.js';

export const LOGICAL_WIDTH = 400;
export const LOGICAL_HEIGHT = 720;

/**
 * Creates the initial default map for Prototype v0.1.
 * 9 territories arranged in a 3-tier mobile-friendly portrait battlefield.
 */
export function createDefaultTerritories(
  playerModifiers: PlayerUpgradeModifiers = {
    startingUnits: 20,
    productionRateMultiplier: 1,
    armySpeedMultiplier: 1,
  },
  enemyModifiers: PlayerUpgradeModifiers = {
    startingUnits: 20,
    productionRateMultiplier: 1,
    armySpeedMultiplier: 1,
  }
): Record<string, Territory> {
  return {
    'p_base': {
      id: 'p_base',
      name: 'Player Fortress',
      x: 200,
      y: 610,
      radius: 36,
      owner: 'player',
      units: playerModifiers.startingUnits,
      maxUnits: 65,
      productionRate: 1.2 * playerModifiers.productionRateMultiplier,
      tier: 3,
      type: 'fortress',
    },
    'e_base': {
      id: 'e_base',
      name: 'Enemy Citadel',
      x: 200,
      y: 110,
      radius: 36,
      owner: 'enemy',
      units: enemyModifiers.startingUnits,
      maxUnits: 65,
      productionRate: 1.2 * enemyModifiers.productionRateMultiplier,
      tier: 3,
      type: 'fortress',
    },
    'n_bot_left': {
      id: 'n_bot_left',
      name: 'Southwest Barracks',
      x: 85,
      y: 485,
      radius: 27,
      owner: 'neutral',
      units: 8,
      maxUnits: 40,
      productionRate: 0.9,
      tier: 1,
      type: 'barracks',
    },
    'n_bot_right': {
      id: 'n_bot_right',
      name: 'Southeast Stable',
      x: 315,
      y: 485,
      radius: 27,
      owner: 'neutral',
      units: 8,
      maxUnits: 40,
      productionRate: 0.9,
      tier: 1,
      type: 'stable',
    },
    'n_center': {
      id: 'n_center',
      name: 'Crown Keep',
      x: 200,
      y: 360,
      radius: 32,
      owner: 'neutral',
      units: 14,
      maxUnits: 55,
      productionRate: 1.1,
      tier: 2,
      type: 'fortress',
    },
    'n_mid_left': {
      id: 'n_mid_left',
      name: 'West Barracks',
      x: 75,
      y: 360,
      radius: 26,
      owner: 'neutral',
      units: 10,
      maxUnits: 40,
      productionRate: 0.85,
      tier: 1,
      type: 'barracks',
    },
    'n_mid_right': {
      id: 'n_mid_right',
      name: 'East Barracks',
      x: 325,
      y: 360,
      radius: 26,
      owner: 'neutral',
      units: 10,
      maxUnits: 40,
      productionRate: 0.85,
      tier: 1,
      type: 'barracks',
    },
    'n_top_left': {
      id: 'n_top_left',
      name: 'Northwest Stable',
      x: 85,
      y: 235,
      radius: 27,
      owner: 'neutral',
      units: 8,
      maxUnits: 40,
      productionRate: 0.9,
      tier: 1,
      type: 'stable',
    },
    'n_top_right': {
      id: 'n_top_right',
      name: 'Northeast Barracks',
      x: 315,
      y: 235,
      radius: 27,
      owner: 'neutral',
      units: 8,
      maxUnits: 40,
      productionRate: 0.9,
      tier: 1,
      type: 'barracks',
    },
  };
}
